name: Deploy to gh-pages

on: 
  [release, workflow_dispatch]
env:
  NUXT_APP_CDN_URL: https://esciencecenter-digital-skills.github.io/${{ github.event.repository.name }}
jobs:
  deploy_with_NEBULA:
    permissions: 
      contents: write
    uses: esciencecenter-digital-skills/NEBULA/.github/workflows/deploy.yml@v0.4.2
    with:
      content_organization: esciencecenter-digital-skills
      content_repository: ${{ github.event.repository.name }}
      content_ref: update_module_format
      base_url: ${{ github.event.repository.name }}
      nebula_ref: v0.4.2
